
# DB properties
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/comm-testing-old"
    username: "root"
    password: "password"
    driver-class-name: org.mariadb.jdbc.Driver

# ModBus client configuration

# Scheduling properties
connectionHandlingTask: "*/15 * * * * ?"
dataProcessingTask: "0 */1 * * * ?"